[providers]
infisical = { type = "infisical", project_id = "52838648-6a12-479a-bad9-6e3543df4998", environment = "prod", path = "/" }

[secrets]
GITHUB_CLIENT_ID = { provider = "infisical", value = "GITHUB_CLIENT_ID" }
GITHUB_CLIENT_SECRET = { provider = "infisical", value = "GITHUB_CLIENT_SECRET" }
